import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { 
  ShoppingCart, 
  CheckCircle2, 
  Plus, 
  Loader2,
  Terminal,
  Download,
  Trash2
} from "lucide-react";
import DashboardLayout from "../layouts/DashboardLayout";
import Topbar from "../components/Topbar";
import { getCurrentShoppingListApi, addPantryItemApi, clearShoppingListApi } from "../api/api";
import type { ShoppingList } from "../api/api";

export default function ShoppingListPage() {
    const [shoppingList, setShoppingList] = useState<ShoppingList | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [restockedItems, setRestockedItems] = useState<Set<string>>(new Set());
    const [restockingAll, setRestockingAll] = useState(false);
    const [clearing, setClearing] = useState(false);

    useEffect(() => {
        let active = true;
        (async () => {
            try {
                setLoading(true);
                const res = await getCurrentShoppingListApi();
                if (active) {
                    setShoppingList(res.shoppingList);
                }
            } catch (err: any) {
                if (active) setError(err?.message || "Failed to load shopping list.");
            } finally {
                if (active) setLoading(false);
            }
        })();
        return () => { active = false; };
    }, []);

    async function restockItem(item: ShoppingList["items"][number]) {
        if (!item.ingredientId) {
            setError(`"${item.name}" not linked. Please add it manually in the Pantry.`);
            return;
        }
        try {
            await addPantryItemApi({ ingredientId: item.ingredientId, quantity: item.quantity || 1, unit: item.unit || "pcs" });
            setRestockedItems(prev => new Set(prev).add(item.name));
        } catch (e: any) {
            setError(e?.message || `Failed to add ${item.name} to pantry.`);
        }
    }

    async function restockAll() {
        if (!shoppingList?.items.length) return;
        const linked = shoppingList.items.filter(i => i.ingredientId);
        if (!linked.length) { setError("No items to add."); return; }
        try {
            setRestockingAll(true); 
            setError(null);
            await Promise.all(linked.map(i => addPantryItemApi({ ingredientId: i.ingredientId!, quantity: i.quantity || 1, unit: i.unit || "pcs" })));
            setRestockedItems(new Set(linked.map(i => i.name)));
        } catch (e: any) {
            setError(e?.message || "Failed to update pantry.");
        } finally {
            setRestockingAll(false);
        }
    }

    const handleClearAll = async () => {
        if (!window.confirm("Are you sure you want to clear your entire list?")) return;
        try {
            setClearing(true);
            await clearShoppingListApi();
            setShoppingList(null);
        } catch (err) {
            console.error("Clear list error", err);
        } finally {
            setClearing(false);
        }
    };

    const exportShoppingList = () => {
        if (!shoppingList || !shoppingList.items.length) return;
        
        let content = `SMARTPANTRY SHOPPING LIST\n`;
        content += `----------------------------------------\n\n`;
        
        shoppingList.items.forEach(item => {
            content += `[ ] ${item.name.toUpperCase()} - ${item.quantity} ${item.unit}\n`;
        });
        
        content += `\n----------------------------------------\n`;
        content += `Generated by SmartPantry`;

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `Shopping_List.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <DashboardLayout topbar={(openMenu) => (
            <Topbar 
                onOpenMenu={openMenu}
                customTitle={
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center text-white shadow-lg shadow-blue-200">
                           <ShoppingCart size={20} />
                        </div>
                        <div>
                           <h1 className="text-xl font-bold tracking-tight text-slate-800 uppercase">Shopping List</h1>
                           <p className="text-[10px] font-bold text-slate-400 tracking-widest uppercase">Manage your weekly needs</p>
                        </div>
                    </div>
                }
            />
        )}>
            <div className="max-w-2xl mx-auto pb-12 pt-8">
                {error && (
                    <div className="mb-6 p-4 rounded-2xl bg-red-50 border border-red-100 text-red-600 text-[10px] font-bold uppercase tracking-widest flex items-center justify-between">
                        <div>{error}</div>
                        <button onClick={() => setError(null)} className="opacity-40 hover:opacity-100 transition-opacity">✕</button>
                    </div>
                )}

                <div className="bg-[#FAFDFF] border border-slate-200 rounded-3xl space-y-8 p-8 shadow-md">
                   <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-50 pb-4 gap-4">
                      <div className="flex items-center gap-3">
                         <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600"><ShoppingCart size={20} /></div>
                         <div>
                            <h3 className="text-sm font-bold uppercase tracking-widest text-slate-900">Grocery List</h3>
                            <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Items to buy</p>
                         </div>
                      </div>
                      <div className="flex items-center gap-2">
                        {shoppingList && shoppingList.items.length > 0 && (
                          <button className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-50 border border-slate-200 text-slate-600 text-[9px] font-bold uppercase tracking-widest hover:bg-slate-100 transition-all" onClick={exportShoppingList}>
                             <Download size={12} /> Export
                          </button>
                        )}
                        {shoppingList && shoppingList.items.length > 0 && (
                            <button 
                                onClick={handleClearAll}
                                disabled={clearing}
                                className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-red-50 text-red-600 text-[9px] border border-red-100 font-bold uppercase tracking-widest hover:bg-red-100 transition-all"
                            >
                                {clearing ? <Loader2 size={12} className="animate-spin" /> : <Trash2 size={12} />}
                                Clear All
                            </button>
                        )}
                        {shoppingList && shoppingList.items.length > 0 && (
                          <button className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-emerald-50 border border-emerald-100 text-emerald-600 text-[9px] font-bold uppercase tracking-widest hover:bg-emerald-600 hover:text-white transition-all group" onClick={restockAll} disabled={restockingAll}>
                             {restockingAll ? <Loader2 className="animate-spin" size={12} /> : <Plus size={12} className="group-hover:rotate-90 transition-transform" />}
                             Restock All
                          </button>
                        )}
                      </div>
                   </div>

                   {loading ? (
                       <div className="py-12 flex items-center justify-center">
                           <Loader2 className="animate-spin text-blue-600" size={32} />
                       </div>
                   ) : !shoppingList || !shoppingList.items.length ? (
                      <div className="py-12 flex flex-col items-center text-center space-y-4">
                         <div className="w-16 h-16 rounded-full bg-emerald-50 flex items-center justify-center text-emerald-600">
                            <CheckCircle2 size={32} />
                         </div>
                         <div className="space-y-1">
                            <p className="text-xs font-bold text-slate-900 uppercase tracking-widest">Everything's here!</p>
                            <p className="text-[10px] text-slate-400 font-medium">You have all the ingredients you need.</p>
                         </div>
                      </div>
                   ) : (
                      <div className="max-h-[500px] overflow-y-auto pr-2 space-y-3 custom-scrollbar">
                        {shoppingList.items.map((item, idx) => {
                          const done = restockedItems.has(item.name);
                          return (
                            <motion.div 
                              initial={{ opacity: 0, x: 20 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ delay: idx * 0.05 }}
                              className={`flex items-center justify-between p-4 rounded-2xl border transition-all
                                ${done 
                                  ? "bg-emerald-50 border-emerald-100 opacity-60" 
                                  : "bg-slate-50 border-slate-200 hover:border-slate-200 shadow-md"}`}
                              key={`${item.name}-${idx}`}
                            >
                              <div className="space-y-1">
                                 <p className={`text-xs font-bold uppercase transition-colors ${done ? "text-emerald-600" : "text-slate-900"}`}>{item.name}</p>
                                 <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">{item.quantity} {item.unit}</p>
                              </div>
                              <button 
                                className={`w-8 h-8 rounded-lg flex items-center justify-center transition-all
                                  ${done 
                                    ? "bg-emerald-600 text-white shadow-md" 
                                    : "bg-[#FAFDFF] border border-slate-200 text-slate-400 hover:text-blue-600 hover:border-blue-100 shadow-md"}`}
                                onClick={() => restockItem(item)} 
                                disabled={done}
                              >
                                {done ? <CheckCircle2 size={14} /> : <Plus size={14} />}
                              </button>
                            </motion.div>
                          );
                        })}
                      </div>
                   )}

                   <div className="pt-6 border-t border-slate-50">
                      <div className="flex items-center gap-3 p-4 rounded-2xl bg-blue-50 border border-blue-100 shadow-md">
                         <Terminal size={14} className="text-blue-400" />
                         <p className="text-[9px] font-bold text-blue-600 uppercase tracking-widest leading-relaxed">Note: Added items will appear in your kitchen pantry immediately.</p>
                      </div>
                   </div>
                </div>

            </div>
        </DashboardLayout>
    );
}
